const mongoose = require("mongoose");

const JobSchema = new mongoose.Schema(
  {
    // Core Fields
    employerId: { type: String, required: true },
    jobTitle: { type: String, required: true },
    jobDescription: { type: String, required: true },
    jobCategory: { type: String, default: "" },
    jobSubCategory: { type: String, default: "" },
    employmentTypes: [{ type: String }],
    workplaceType: { type: String, default: "" },
    location: { type: Object, default: {} },
    companyId: { type: String, default: "" },
    salaryRange: { type: Object, default: {} },
    experienceRequired: { type: String, default: "" },
    positionLevel: { type: String, default: "" },
    specializations: [{ type: String }],
    isRemote: { type: Boolean, default: false },
    applicationCount: { type: Number, default: 0 },
    status: { type: String, default: "Open" },
    jobImages: [{ type: String }],

    // Suggested / Additional Fields
    requiredSkills: [{ type: String }],
    benefits: [{ type: String }],
    applicationDeadline: { type: Date },
    positionsAvailable: { type: Number, default: 1 },
    industry: { type: String, default: "" },
    jobTags: [{ type: String }],
    remotePercentage: { type: Number, default: 0 },
    acceptsExternalApplications: { type: Boolean, default: true },
    requiredDocuments: [{ type: String }],
    salaryType: { type: String, default: "Monthly" },
    isFeatured: { type: Boolean, default: false },
    sponsoredUntil: { type: Date },
    viewsCount: { type: Number, default: 0 },
    clicksCount: { type: Number, default: 0 },
    applicationLink: { type: String },
    isUrgent: { type: Boolean, default: false },
    isRemoteFriendly: { type: Boolean, default: false },

    // Extended Fields
    isPublic: { type: Boolean, default: true },
    visibleToRoles: [{ type: String }],
    recruiterName: { type: String, default: "" },
    recruiterEmail: { type: String, default: "" },
    recruiterPhone: { type: String, default: "" },
    badges: [{ type: String }],
    companySize: { type: String, default: "" },
    foundedYear: { type: Number },
    companyWebsite: { type: String, default: "" },
    companyIndustry: { type: String, default: "" },
    companyLogo: { type: String, default: "" },
    responsibilities: [{ type: String }],
    qualifications: [{ type: String }],
    niceToHave: [{ type: String }],
    timezone: { type: String, default: "" },
    officeAddress: { type: String, default: "" },
    applicationsViewed: { type: Number, default: 0 },
    applicationsShortlisted: { type: Number, default: 0 },
    shareCount: { type: Number, default: 0 },
    isExpired: { type: Boolean, default: false },
    archivedAt: { type: Date },
    bonus: { type: String, default: "" },
    equity: { type: String, default: "" },
    salaryFrequency: { type: String, default: "Monthly" },
    allowMultipleApplications: { type: Boolean, default: true },
    allowVideoResume: { type: Boolean, default: false },
    seoTags: [{ type: String }],
    recommendedForRoles: [{ type: String }],
    isSponsored: { type: Boolean, default: false },
    promotionEndDate: { type: Date },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Job", JobSchema);
